{% set name = "userpath" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcd66c5fa9b1a3c12362f309bbb5bc7992bac8af86d17b4e6b1a4b166a11c43f

build:
  number: 1
  noarch: python
  entry_points:
    - userpath = userpath.cli:userpath
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - python >={{ python_min }}

test:
  imports:
    - userpath
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - userpath --help
    - pip check

about:
  home: https://github.com/ofek/userpath
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Cross-platform tool for adding locations to the user PATH, no elevated privileges required!
  dev_url: https://github.com/ofek/userpath

extra:
  recipe-maintainers:
    - mariusvniekerk
