{% set name = "userpath" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04233d2fcfe5cff911c1e4fb7189755640e1524ff87a4b82ab9d6b875fee5787

build:
  number: 0
  noarch: python
  entry_points:
    - userpath = userpath.cli:userpath
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - hatchling >=1.3.0
  run:
    - click
    - python >=3.7

test:
  imports:
    - userpath
  requires:
    - pip
  commands:
    - userpath --help
    - pip check

about:
  home: https://github.com/ofek/userpath
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Cross-platform tool for adding locations to the user PATH, no elevated privileges required!
  dev_url: https://github.com/ofek/userpath

extra:
  recipe-maintainers:
    - mariusvniekerk
